# Generated by Django 3.0.4 on 2020-03-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200321_0739'),
        ('products', '0007_product_slug'),
    ]

    operations = [
    ]
